global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"

scrape_configs:
  - job_name: "prometheus"
    static_configs:
      - targets: ["localhost:9090"]

  - job_name: "kafka"
    static_configs:
      - targets: ["kafka1:9101", "kafka2:9102"]

  - job_name: "spark-master"
    static_configs:
      - targets: ["spark-master:8080"]

  - job_name: "hadoop-namenode"
    static_configs:
      - targets: ["namenode:9870"]

  - job_name: "hadoop-datanode"
    static_configs:
      - targets: ["datanode:9864"]
