# Wildtrack Kafka Producer Configuration

# Kafka Settings
kafka:
  bootstrap_servers:
    - "localhost:9092"
    - "localhost:9093"
  topics:
    cam1: "cam1-feed"
    cam2: "cam2-feed" 
    cam3: "cam3-feed"
    cam4: "cam4-feed"
    cam5: "cam5-feed"
    cam6: "cam6-feed"
    cam7: "cam7-feed"

# Dataset Settings  
dataset:
  path: "../data/wildtrack"
  cameras: ["cam1", "cam2", "cam3", "cam4", "cam5", "cam6", "cam7"]
  
# Streaming Settings
streaming:
  fps: 10
  quality: 85  # JPEG compression quality
  max_frames_test: 100  # For testing purposes
  
# Grid Configuration (Wildtrack specific)
grid:
  width: 480
  height: 1440
  spacing: 0.025  # 2.5cm
  origin_x: -3.0
  origin_y: -9.0

# Performance Settings
performance:
  buffer_memory: 33554432  # 32MB
  batch_size: 16384
  linger_ms: 10
  compression: "gzip"
